const STORIES = {
  pets: [
    ["{name} has a little cat.", "The cat is soft and white.", "{name} loves to pet the cat every day."],
    ["{name} has a big dog.", "The dog wags its tail and jumps.", "They play fetch in the yard together."],
    ["{name} has a tiny fish.", "The fish swims round and round.", "{name} watches the fish before bed."],
    ["{name} has a fluffy rabbit.", "The rabbit hops all over the grass.", "{name} feeds it carrots and smiles."],
    ["{name} has a green turtle.", "The turtle moves nice and slow.", "{name} thinks the turtle is very cute."],
    ["{name} has a yellow bird.", "The bird sings a happy song.", "{name} sings along with the bird."],
    ["{name} has a little hamster.", "The hamster runs on its wheel all night.", "{name} laughs and watches it spin."],
  ],
  farm: [
    ["{name} visits a big farm.", "There are cows, pigs, and hens.", "{name} loves to feed the animals."],
    ["{name} sees a fluffy sheep.", "The sheep says baa and runs away.", "{name} laughs and runs after it."],
    ["{name} finds a baby chick.", "The chick is yellow and very small.", "{name} holds it gently in both hands."],
    ["{name} rides a big horse.", "The horse trots slowly down the path.", "{name} holds on tight and grins."],
    ["{name} collects eggs from the hens.", "The eggs are warm and smooth.", "{name} puts them in a big basket."],
    ["{name} sees a pig in the mud.", "The pig rolls and snorts with joy.", "{name} thinks pigs are very funny."],
    ["{name} watches a cow eat grass.", "The cow moos very loudly.", "{name} moos back and the cow looks up."],
  ],
  ocean: [
    ["{name} goes to the beach.", "The waves splash on the sand.", "{name} digs a big hole with a spade."],
    ["{name} finds a pretty shell.", "The shell is pink and shiny.", "{name} holds it up to hear the sea."],
    ["{name} sees a bright starfish.", "The starfish has five long arms.", "{name} puts it back in the water gently."],
    ["{name} watches a crab walk.", "The crab moves side to side.", "{name} thinks that looks very funny."],
    ["{name} jumps in the blue waves.", "The water is cold and fun.", "{name} laughs and splashes all day."],
    ["{name} sees a big fish swim by.", "The fish has yellow and blue stripes.", "{name} waves hello to the fish."],
    ["{name} builds a big sandcastle.", "The castle has towers and a door.", "A wave knocks it down and {name} laughs."],
  ],
  space: [
    ["{name} looks up at the night sky.", "The stars twinkle and shine bright.", "{name} counts ten stars before bed."],
    ["{name} draws a big rocket ship.", "The rocket is red and very fast.", "{name} wants to fly to the moon one day."],
    ["{name} sees the big round moon.", "The moon glows white in the dark.", "{name} waves good night to the moon."],
    ["{name} reads about the planets.", "There are eight planets in our sky.", "{name} loves big red Mars the best."],
    ["{name} pretends to be an astronaut.", "{name} puts on a helmet and suit.", "{name} floats around with a big smile."],
    ["{name} sees a shooting star.", "It zips fast across the sky.", "{name} makes a wish and closes both eyes."],
    ["{name} looks at the sun safely.", "The sun is a giant ball of fire.", "{name} draws a big sun with yellow rays."],
  ],
  weather: [
    ["{name} wakes up to a sunny day.", "The sky is blue and very bright.", "{name} goes outside to play in the sun."],
    ["{name} sees big grey clouds.", "The clouds bring a soft warm rain.", "{name} dances in the puddles."],
    ["{name} sees snow fall from the sky.", "The snow is cold and very white.", "{name} makes a big round snowman."],
    ["{name} hears thunder rumble loud.", "Lightning flashes in the dark sky.", "{name} watches safely from inside."],
    ["{name} feels a cool breeze blow.", "The wind lifts the leaves up high.", "{name} flies a kite in the park."],
    ["{name} sees a big rainbow.", "It has red, yellow, green, and blue.", "{name} tries to find its end."],
    ["{name} feels the warm spring sun.", "The flowers start to bloom and grow.", "{name} smells the flowers and smiles."],
  ],
  food: [
    ["{name} helps make a yummy pizza.", "They put cheese and sauce on top.", "{name} takes a big bite and says mmm."],
    ["{name} picks red apples from a tree.", "The apples are sweet and very crisp.", "{name} eats one and saves one for later."],
    ["{name} makes a big fruit salad.", "There are grapes, berries, and melon.", "{name} shares it with the whole family."],
    ["{name} bakes soft cookies with mum.", "The cookies smell so good in the oven.", "{name} waits until they are cool."],
    ["{name} eats a big bowl of soup.", "The soup is warm and full of veggies.", "{name} feels happy and full after lunch."],
    ["{name} makes a peanut butter sandwich.", "{name} spreads it thick on soft bread.", "It is the best sandwich ever."],
    ["{name} tries a new green vegetable.", "It is crunchy and a little bit sweet.", "{name} is surprised and asks for more."],
  ],
  school: [
    ["{name} walks to school with a smile.", "The classroom is bright and colorful.", "{name} finds a seat next to a friend."],
    ["{name} learns to write new letters.", "Each letter has its own fun shape.", "{name} practises until every letter is neat."],
    ["{name} reads a book at storytime.", "The story is about a brave little bear.", "{name} listens quietly and loves every page."],
    ["{name} paints a picture in art class.", "The picture has a big sun and green trees.", "{name} hangs it on the classroom wall."],
    ["{name} plays with friends at recess.", "They run and laugh on the playground.", "{name} goes back to class feeling happy."],
    ["{name} counts to twenty in math.", "{name} uses fingers to help count along.", "The teacher says well done and claps."],
    ["{name} learns a new song at school.", "The song is about the days of the week.", "{name} sings it all the way home."],
  ],
  family: [
    ["{name} loves spending time with family.", "Mum reads a story every single night.", "{name} falls asleep with a big smile."],
    ["{name} helps dad cook dinner tonight.", "They make a big pot of yummy soup.", "{name} stirs the pot and tastes a spoonful."],
    ["{name} plays a game with big sister.", "They laugh and take turns rolling the dice.", "{name} wins and does a happy dance."],
    ["{name} goes for a walk with grandpa.", "They look at birds and big old trees.", "{name} holds grandpa's hand the whole way."],
    ["{name} helps set the table for dinner.", "{name} puts a fork and spoon at every seat.", "The family eats together."],
    ["{name} and mum bake a birthday cake.", "They mix the batter and pour it in a pan.", "{name} licks the spoon and grins."],
    ["{name} plays in the yard with brothers.", "They chase each other round and round.", "Dad watches and laughs from the porch."],
  ],
  nature: [
    ["{name} walks in the green forest.", "Tall trees rise up all around.", "{name} listens to the birds and the wind."],
    ["{name} finds a little caterpillar.", "It crawls slowly on a big green leaf.", "{name} watches carefully and does not touch."],
    ["{name} sees a butterfly land nearby.", "Its wings are orange, black, and white.", "{name} stays very still so it won't fly away."],
    ["{name} splashes in a shallow stream.", "The water is cool and very clear.", "{name} sees tiny fish dart between the stones."],
    ["{name} plants a seed in the garden.", "{name} waters it a little every morning.", "One day a little green sprout pops up."],
    ["{name} lies in the soft green grass.", "Clouds float slowly across the blue sky.", "{name} sees a cloud shaped like a bear."],
    ["{name} collects pretty autumn leaves.", "The leaves are red, orange, and gold.", "{name} presses them flat inside a big book."],
  ],
  sports: [
    ["{name} kicks a ball into the goal.", "Everyone cheers and claps very loud.", "{name} runs around with both arms up high."],
    ["{name} learns to ride a bicycle.", "At first {name} wobbles a little bit.", "Soon {name} rides all the way down the path."],
    ["{name} swims across the big pool.", "{name} kicks fast and uses both arms.", "The teacher says that was amazing."],
    ["{name} hits a ball with a big bat.", "The ball flies up into the blue sky.", "{name} runs as fast as possible to first base."],
    ["{name} shoots a basket in gym class.", "The ball spins round the rim and goes in.", "{name} jumps up and gives a big high five."],
    ["{name} does a cartwheel on the grass.", "Both legs swing up straight and tall.", "Everyone claps and {name} takes a bow."],
    ["{name} runs a race on sports day.", "{name} pumps both arms and goes very fast.", "{name} crosses the line and gets a ribbon."],
  ],
};
